### PR TITLE
raise exception if user tries to pass large object by value

### PR DESCRIPTION
**Pull request by robertnishihara**

### CODE REVIEW

**Comment by mehrdadn** [comment]
Exception seems harsh. Why not make it a [warning](https://docs.python.org/2/library/warnings.html)?

**Comment by robertnishihara** [comment]
Well an exception is less harsh than a fatal error :)

I guess I imagine warnings being missed. And if this proves too restrictive, then we'll definitely hear about it.

**Comment by mehrdadn** [comment]
It's no different from a fatal error here, because it's not the kind of exception the user would ever catch during runtime. Exceptions mean the programmer is in error, and they cannot be suppressed. Warnings mean the code will do what is asked without causing an error, but the programmer should probably be doing something else. You clearly mean the latter, so why say the former?

**Comment by mehrdadn** [comment]
Also, note that it's kind of hard to miss Python warnings when you're in a shell. I'm not sure if you have before, but I never have.

**Pull request merged**
