### PR TITLE
Retry registering workers better

### PR DESCRIPTION
**Pull request by mehrdadn**

### CODE REVIEW

**Comment by robertnishihara** [comment]
What's the right way to test this. Normally, I can start a scheduler, object store, and worker with the following steps:

1. `build/scheduler 127.0.0.1:10001`
2. `build/objstore 127.0.0.1:10001 127.0.0.1:20001`
3. `python scripts/default_worker.py --scheduler-address 127.0.0.1:10001 --objstore-address 127.0.0.1:20001 --worker-address 127.0.0.1:40001`

I thought this would let me start the worker first, but running the command
```
python default_worker.py --scheduler-address 127.0.0.1:10001 --objstore-address 127.0.0.1:20001 --worker-address 127.0.0.1:40001
```
on its own fails with 
```
E0727 13:55:32.355731000 140735238365184 client_context.cc:94] assertion failed: call_ == nullptr
Abort trap: 6
```

**Comment by mehrdadn** [comment]
Ah, I was forgetting to use a new context for every call. I've fixed it now.

**Comment by robertnishihara** [comment]
Ok, this looks right.

Notes:

- If I start a worker (without a scheduler or an object store), then the worker doesn't die or anything like that. I would have expected it to die after 3 seconds, but it seems to go indefinitely. To probe this, I had the worker print something every time it retried. You'd think that it happens every 20 milliseconds, but actually it starts out pretty slow and gRPC may do some sort of exponential back off, because I've been waiting for a while and it has only retried 10 times. At the very least, the timing is misleading.

- I added an additional commit. This change allows me to start a worker, then a scheduler, then an object store (in that order). I can then attach a shell, define a remote function, call it, etc.

**Comment by mehrdadn** [comment]
Oh yeah! I noticed the gRPC retries. Somehow it didn't really bother me enough to do anything about it though so I forgot. Is there anything you want to do about it, or do you want to leave it as is? We could try measuring time, or we could retry for a fixed number of times.

The commit looks fine too... in fact, I think I had that exact commit lurking in my stash a while back, I just never ended up putting it in.

**Comment by robertnishihara** [comment]
I'd say retry for a fixed number of times. Maybe like 5 (that might work out to about 10 seconds)? And 10 retries would be multiple minutes.

**Comment by mehrdadn** [comment]
Updated.

**Pull request merged**
