### PR TITLE
Remove type information from remote decorator.

### PR DESCRIPTION
**Pull request by robertnishihara**

### CODE REVIEW

**Comment by mehrdadn** [comment]
If you remove one level of function call, you should make it `@ray.remote` rather than `@ray.remote()`.

**Comment by robertnishihara** [comment]
We want to pass in the number of return values, so that people have the option of doing

```python
@ray.remote(num_return_vals=2)
def plus_and_minus(a, b):
  return a + b, a - b
```

**Comment by mehrdadn** [comment]
Hm, we could make both of them work, right? See [here](http://stackoverflow.com/q/653368).

**Comment by pcmoritz** [comment]
I like this suggestion, @ray.remote is much more natural than @ray.remote() if there is only one return argument!

**Pull request merged**
