### PR TITLE
Unify starting local cluster with attaching to existing cluster

### PR DESCRIPTION
**Pull request by robertnishihara**
There are two scenarios.

1. There is an existing Ray cluster, and a script wants to attach to that cluster.
2. There is no existing Ray cluster, and the script needs to start one.

Scripts should be able to handle both cases with little or no modification. With this PR, you use the `ray.init` command for both cases. For case 1, you do something like

```python
ray.init(scheduler_address="172.31.34.131:10001", objstore_address="172.31.34.131:20001", driver_address="172.31.34.131:30001")
```

For case 2, you do something like
```python
ray.init(start_ray_local=True, num_workers=2)
```

This PR also removes `scripts/shell.py`.

### CODE REVIEW

**Comment by mehrdadn** [comment]
`context` is unintuitive. I would call the two methods `ray.connect` and `ray.initialize`, respectively. If you must call them the same thing (which I do not recommend), call both of them `initialize`.

**Comment by mehrdadn** [comment]
Why the `start_ray_local=True`? What would it mean to say `start_ray_local=False`? It seems like the default should be to start something locally.

Also, (why) do you need to pass all 3 addresses? If this is for a driver, what does `objstore_address` mean (which object store)? If this is for the worker, why does it need the driver address? It seems weird to be able to pass in everything simultaneously since it seems like that should never be needed.

**Comment by pcmoritz** [comment]
To answer the questions: 

"start_local" is in contrast to "attach to an existing cluster". For starting a cluster, we have a separate script, cluster.py.

For attaching to a cluster, in the future we will have a etcd/zookeeper instance running that will assign these addresses, so we will only need a single IP address. For now it makes sense to keep the current behavior I think, which is just passing in the three addresses that are needed.

**Comment by pcmoritz** [comment]
We should make it really clear that no matter if a local ray instance is started, or if we connect to an existing cluster, the program is exactly the same. That's the reason why having only one method is preferable. I agree that naming is difficult and maybe ray.initialize or ray.init is preferable to ray.context.

**Comment by mehrdadn** [comment]
Hm, I don't understand why the naming of the method implies anything about the rest of the program being the same/different. However, I would say that the most "correct" thing to do here is to make a Ray class that can be constructed by the user in different ways, so that the result is always a Ray instance. That also has the benefit of not having global state/singleton, which is a good thing.

**Comment by robertnishihara** [comment]
Fixed "context -> init".

**Comment by mehrdadn** [comment]
(y)

**Pull request merged**
