### PR TITLE
only let creator of message queue deallocate message queue

### PR DESCRIPTION
**Pull request by robertnishihara**

### CODE REVIEW

**Comment by mehrdadn** [comment]
Don't forget to add it to

	MessageQueue<>::operator=()

**Comment by mehrdadn** [comment]
Also, `create_` should only be set on success, right? You don't want to remove a message queue that you didn't actually create.

**Comment by robertnishihara** [comment]
Fixed. Thanks!

**Comment by mehrdadn** [comment]
LGTM, can merge once tests pass.

**Comment by robertnishihara** [comment]
Awesome, thanks!

**Pull request merged**
